FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app
RUN rm -rf packages/sinkron-client
RUN rm -rf packages/front
RUN pnpm install --frozen-lockfile
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build-app
WORKDIR /app
EXPOSE 80
ENV SINKRON_DB_PATH="/app/mount"
CMD ["pnpm", "start-app"]
