FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app
RUN rm -rf packages/benchmark
RUN rm -rf packages/client
RUN rm -rf packages/front
RUN rm -rf packages/tauri
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run app:build
WORKDIR /app
EXPOSE 80
CMD ["pnpm", "app:start"]
