FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app
RUN rm -rf packages/benchmark
RUN rm -rf packages/client
RUN rm -rf packages/front
RUN rm -rf packages/tauri
RUN --mount=type=cache,id=node22pnpm9,target=/pnpm/store pnpm install --frozen-lockfile
RUN node --run app:build
WORKDIR /app
EXPOSE 80
CMD node --run app:start
