FROM node:20-alpine AS build
RUN corepack enable
COPY . /app
WORKDIR /app
# RUN rm -rf packages/sinkron
RUN rm -rf packages/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build-front

FROM nginx:alpine
ENV STATIC_FILES_URL="/static"
ENV API_REWRITE_URL="https://api.sinkron.xyz/"
COPY nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/packages/front/build /app
RUN chmod -R 777 /app

