FROM node:20-alpine AS base
RUN corepack enable
COPY . /app
WORKDIR /app
RUN rm -rf packages/sinkron-client
RUN rm -rf packages/paper-front
RUN pnpm install --frozen-lockfile
RUN pnpm run build-backend
WORKDIR /app/packages/paper-back
EXPOSE 80
CMD ["pnpm", "start"]
