version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinkron
