version: "3.9"

services:
    postgres:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=sinkron
        command: ["postgres", "-c", "log_statement=all"]
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U postgres -d sinkron"
                ]
            interval: 3s
            retries: 3
            start_period: 3s
            timeout: 3s
    sinkron:
        build: ../../rust
        ports:
            - 3000:80
        environment:
            - SINKRON_CONFIG=${SINKRON_CONFIG}
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
