version: '3.9'

services:
  sinkron_postgres:
    image: postgres:17-alpine
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinkron

  app_postgres:
    image: postgres:17-alpine
    ports:
      - 5002:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinkron_app
