version: "3.9"

services:
    postgres_sinkron:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=sinkron
        command: postgres -c log_statement=all
        healthcheck:
            test: pg_isready
            interval: 3s
            retries: 3
            start_period: 3s
            timeout: 3s

    sinkron:
        build: ../../sinkron
        environment:
            RUST_LOG: sinkron=trace
            SINKRON_CONFIG: >
                {
                    "host": "0.0.0.0",
                    "port": 80,
                    "apiToken": "SINKRON_API_TOKEN",
                    "syncAuthUrl": "-",
                    "db": {
                        "host": "postgres_sinkron",
                        "port": 5432,
                        "user": "postgres",
                        "password": "password",
                        "database": "sinkron"
                    }
                }
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 3001:80

    postgres:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=sinkron
        command: postgres -c log_statement=all
        healthcheck:
            test: pg_isready
            interval: 3s
            retries: 3
            start_period: 3s
            timeout: 3s
        ports:
            - 5001:5432
