[package]
name = "sinkron"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["ws"] }
base64 = "0.22.1"
bytes = "1.11.1"
chrono = { version = "0.4.43", features = ["serde"] }
deadpool = { version = "0.12.3", features = ["rt_tokio_1"] }
diesel = { version = "2.3.6", features = ["chrono", "uuid"] }
diesel-async = { version = "0.7.4", features = ["async-connection-wrapper", "deadpool", "postgres"] }
diesel_migrations = "2.3.1"
env_logger = "0.11.8"
log = "0.4.29"
loro = "1.10.3"
lru = "0.16.3"
reqwest = "0.13.3"
rust-s3 = { version = "0.37.2", default-features = false, features = ["fail-on-err", "tokio-rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
sinkron-common = { path = "../sinkron-common" }
tokio = { workspace = true, features = ["rt-multi-thread", "time"] } 
uuid = { workspace = true }
