[package]
name = "sinkron-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
uuid = "1.23.4"
sinkron-common = { path = "../sinkron-common" }
reqwest = { version = "0.13.4", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.150"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt", "macros"] }
