version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5003:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinkron
